<?php

/** @var \PHPCuong\CustomerAccount\Block\Form\ForgotPassword $block */
?>
<?php if (!$block->customerIsAlreadyLoggedIn()) : ?>
    <style>
        .customer-popup-forgotpassword {
            display: none;
            z-index: 1000;
        }

        .or-another-selection {
            display: inline-block;
            padding-right: 5px;
        }

        @media(max-width: 767px) {
            .or-another-selection {
                display: block;
                text-align: center;
                margin-bottom: 5px;
            }
        }
    </style>
    <div id="customer-popup-forgotpassword" class="customer-popup-forgotpassword">
        <div class="block block-customer-forgotpassword">
            <div class="block-content" aria-labelledby="block-customer-popup-forgotpassword-heading">
                <form class="form form-forgotpassword" action="<?= $block->getPostActionUrl() ?>" method="post" id="customer-popup-forgotpassword-form" data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey'); ?>
                    <input type="hidden" name="redirect_url" value="<?= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
                    <fieldset class="fieldset forgotpassword" data-hasrequired="<?= __('* Required Fields') ?>">
                        <div class="field note">
                            <?= __('Please enter your email address below to receive a password reset link.') ?>
                        </div>
                        <div class="messages"></div>
                        <div class="field email required">
                            <label class="label" for="email">
                                <span><?= __('Email') ?></span>
                            </label>
                            <div class="control">
                                <input name="email" value="" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="email-forgotpassword" type="email" class="input-text" title="<?= __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action forgotpassword primary" name="send" id="send2-forgotpassword">
                                    <span><?= __('Reset My Password') ?></span>
                                </button>
                            </div>
                            <div class="secondary">
                                <a class="action remind" href="<?= $block->getBackUrl() ?>" id="customer-popup-sign-in">
                                    <span><?= __('Back') ?></span>
                                </a>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
        <script type="text/x-magento-init">
            {
                "#customer-popup-forgotpassword": {
                    "PHPCuong_CustomerAccount/js/action/customer-authentication-popup": {
                        "popupTitle": "<?= __('Forgot Your Password') ?>",
                        "innerWidth": "400"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>